Support Python 3.13
bodono/scs-python pull request #117
Opened 2024-10-15 08:57 UTC by jonadaly

Hi @bodono , I tried to mirror your changes from my previous request to support Python 3.12 / MacOS - now for the new release of Python 3.13!

I've also removed support for Python 3.8 since it's now [end-of-life](https://devguide.python.org/versions/).

2024-10-16 17:24 UTC, bodono commented
Thanks for looking into this @jonadaly ! It looks like one the python 3.9 run on windows is failing, possibly due to an incompatible numpy version, do you have any ideas on how to fix that? Once fixed we can land this!

2024-10-21 12:30 UTC, jonadaly commented
I'm not sure why that's happening - what's weird is that fixing it seems to have broken the 3.12 build! 😆

2024-10-27 12:09 UTC, enzbus commented
@jonadaly @bodono  maybe try to remove the constraint on setuptools here -> https://github.com/bodono/scs-python/blob/d4f99f9bc4d2b6395d81a66a8cd298fd188a6da4/.github/workflows/build.yml#L46 , dependencies may have broken in Conda (version 60 is 3 years old).

2024-11-01 16:50 UTC, bodono commented
> I'm not sure why that's happening - what's weird is that fixing it seems to have broken the 3.12 build! 😆

We could drop support for 3.9 too, that's less than a year from EOL, if we do that and revert back to when 3.12 was working we can land this.

2024-11-01 16:50 UTC, bodono commented
And sorry for the delay in responding! Thanks for putting effort into this.

2024-11-12 16:44 UTC, jonadaly commented
So I've got the CI passing by removing the "legacy build" for >3.11. Not sure how legit that is though - what do you think @bodono ?

2024-11-15 13:03 UTC, bodono requested changes

2024-11-15 13:03 UTC, bodono commented on .github/workflows/build.yml
> +          echo "SINGLE_ACTION_CONFIG=False" >> $GITHUB_ENV
If this is just always False then we can just remove it, and from line 175 below.

2024-11-15 13:04 UTC, bodono commented
Thanks @jonadaly, LGTM after minor update I suggested. Let me know when you think it is ready to merge and I can do it.

2024-11-21 18:03 UTC, bodono approved these changes

2024-11-21 18:04 UTC, bodono commented
Thanks!

2024-11-21 18:04 UTC, merged